### PR TITLE
Add Prometheus and Frontender Magazine

### PR DESCRIPTION
**Pull request by misterioss**

### CODE REVIEW

**Comment by denysdovhan** [comment]
Thank you for contributing!
frontender magazine isn't Ukrainian blog, so please remove it from list and then I'll merge.

**Comment by misterioss** [comment]
Why not? Anton Nemtsev (Chief Editor of Frontender Magazine) is from Ukraine.

**Comment by denysdovhan** [comment]
Nope, I mean resources with Ukrainian publications.

**Comment by misterioss** [comment]
Ok. Done.

**Comment by denysdovhan** [comment]
Merged. You're awesome :+1:

**Pull request merged**
